# Generated by Django 5.2.9 on 2026-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_poll_updated_at_alter_vote_poll_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("poll", "device_id")},
        ),
    ]
