# Generated by Django 5.2.9 on 2026-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_report_device_id_alter_report_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("reason", models.TextField(blank=True)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="poll",
            name="device_id",
            field=models.CharField(default="UNKNOWN_DEVICE", max_length=255),
        ),
        migrations.AddField(
            model_name="report",
            name="reporter_device_id",
            field=models.CharField(
                blank=True, default="ANONYMOUS", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="device_id",
            field=models.CharField(
                blank=True, default="ANONYMOUS", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="device_id",
            field=models.CharField(default="UNKNOWN_DEVICE", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("poll", "reporter_device_id")},
        ),
    ]
