# Generated by Django 5.2.9 on 2026-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_blockeddevice_alter_report_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
