# Generated by Django 5.2.9 on 2026-01-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("push_token", models.CharField(max_length=255)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
