# Generated by Django 5.2.9 on 2026-02-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_devicenotification_delete_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="poll",
            name="categories",
            field=models.ManyToManyField(related_name="polls", to="polls.category"),
        ),
    ]
