# Generated by Django 5.2.9 on 2026-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_category_poll_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocker_device_id", models.CharField(max_length=255)),
                ("blocked_device_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("blocker_device_id", "blocked_device_id")},
            },
        ),
    ]
